spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    initialization-mode: "always"
    plateform: h2
    url: jdbc:h2:mem:storedb;CACHE_SIZE=8192;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password:
    driverClassName: "org.h2.Driver"
  jpa:
    database-platform: "org.hibernate.dialect.H2Dialect"
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update